#!/usr/bin/env python3
"""Generate a Rust module from a NUI (.nstudio) document.

This is a NUI → native code exporter for the Rust runtime target
(NyCore/NyRuntime per ADR-0020). It reads a .nstudio file and produces
a Rust module that defines the component tree as static data.

Usage:
    python3 tools/generate_rust.py <input.nstudio> [output.rs]

The generated Rust code defines:
- Layout, Component, Screen, and Document structs
- Per-screen factory functions (screen_<id>())
- A load() function returning the document as static data

This follows the same pattern as generate_cpp.py and generate_python.py
but targets the Rust side of the Nyrqis platform.

References:
- ADR-0020: language choices (Rust for NyCore/NyRuntime)
- NUI-SCHEMA: component tree structure
"""

import json
import os
import sys
from typing import Any, Dict


def escape_rust_string(s: str) -> str:
    """Escape a string for Rust string literals."""
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\t", "\\t"))


def generate_component(comp: Dict[str, Any], indent: int = 0) -> str:
    """Generate Rust code for a single component."""
    pad = "    " * indent
    comp_id = escape_rust_string(comp.get("id", ""))
    comp_type = escape_rust_string(comp.get("type", ""))
    layout = comp.get("layout", {})
    props = comp.get("properties", {})
    events = comp.get("events", {})
    children = comp.get("children", [])

    lines = []
    lines.append(f"{pad}Component {{")
    lines.append(f'{pad}    id: "{comp_id}",')
    lines.append(f'{pad}    component_type: "{comp_type}",')
    lines.append(f"{pad}    layout: Layout {{")
    lines.append(f"{pad}        x: {layout.get('x', 0.0)}f64,")
    lines.append(f"{pad}        y: {layout.get('y', 0.0)}f64,")
    lines.append(f"{pad}        width: {layout.get('width', 100.0)}f64,")
    lines.append(f"{pad}        height: {layout.get('height', 30.0)}f64,")
    lines.append(f"{pad}    }},")

    # Properties
    if props:
        lines.append(f"{pad}    properties: &[")
        for key, value in props.items():
            k = escape_rust_string(key)
            v = escape_rust_string(str(value))
            lines.append(f'{pad}        ("{k}", "{v}"),')
        lines.append(f"{pad}    ],")
    else:
        lines.append(f"{pad}    properties: &[],")

    # Events
    if events:
        lines.append(f"{pad}    events: &[")
        for key, value in events.items():
            k = escape_rust_string(key)
            v = escape_rust_string(str(value))
            lines.append(f'{pad}        ("{k}", "{v}"),')
        lines.append(f"{pad}    ],")
    else:
        lines.append(f"{pad}    events: &[],")

    # Children
    if children:
        lines.append(f"{pad}    children: &[")
        for child in children:
            lines.append(generate_component(child, indent + 2))
            lines.append(f"{pad},")
        lines.append(f"{pad}    ],")
    else:
        lines.append(f"{pad}    children: &[],")

    lines.append(f"{pad}}}")
    return "\n".join(lines)


def generate_document(doc: Dict[str, Any]) -> str:
    """Generate a complete Rust module from a NUI document."""
    project = doc.get("project", {})
    screens = doc.get("screens", [])
    states = doc.get("states", {})

    lines = []
    lines.append("// Auto-generated by generate_rust.py — DO NOT EDIT")
    lines.append(f"// Source: {project.get('name', 'NUI Document')}")
    lines.append(f"// Version: {doc.get('version', '1.0.0')}")
    lines.append("")
    lines.append("#![allow(dead_code, unused_variables)]")
    lines.append("")

    # Layout struct
    lines.append("/// Layout coordinates for a component.")
    lines.append("#[derive(Debug, Clone, Copy)]")
    lines.append("pub struct Layout {")
    lines.append("    pub x: f64,")
    lines.append("    pub y: f64,")
    lines.append("    pub width: f64,")
    lines.append("    pub height: f64,")
    lines.append("}")
    lines.append("")

    # Component struct
    lines.append("/// A NUI component with its properties and children.")
    lines.append("#[derive(Debug)]")
    lines.append("pub struct Component<'a> {")
    lines.append("    pub id: &'a str,")
    lines.append("    pub component_type: &'a str,")
    lines.append("    pub layout: Layout,")
    lines.append("    pub properties: &'a [(&'a str, &'a str)],")
    lines.append("    pub events: &'a [(&'a str, &'a str)],")
    lines.append("    pub children: &'a [Component<'a>],")
    lines.append("}")
    lines.append("")

    # Screen struct
    lines.append("/// A NUI screen with a root component tree.")
    lines.append("#[derive(Debug)]")
    lines.append("pub struct Screen<'a> {")
    lines.append("    pub id: &'a str,")
    lines.append("    pub width: f64,")
    lines.append("    pub height: f64,")
    lines.append("    pub root: Component<'a>,")
    lines.append("}")
    lines.append("")

    # Document struct
    lines.append("/// The complete NUI document.")
    lines.append("#[derive(Debug)]")
    lines.append("pub struct Document<'a> {")
    lines.append("    pub name: &'a str,")
    lines.append("    pub version: &'a str,")
    lines.append("    pub screens: &'a [Screen<'a>],")
    lines.append("}")
    lines.append("")

    # Generate screen factory functions
    for screen in screens:
        screen_id = escape_rust_string(screen.get("id", ""))
        size = screen.get("size", {})
        root = screen.get("root", {})

        lines.append(f"/// Screen: {screen_id}")
        lines.append(f"pub fn screen_{screen_id}() -> Screen<'static> {{")
        lines.append(f"    Screen {{")
        lines.append(f'        id: "{screen_id}",')
        lines.append(f"        width: {size.get('width', 0.0)}f64,")
        lines.append(f"        height: {size.get('height', 0.0)}f64,")
        lines.append(f"        root: {generate_component(root, 2)},")
        lines.append(f"    }}")
        lines.append(f"}}")
        lines.append("")

    # Generate document constructor
    screen_names = [escape_rust_string(s.get("id", "")) for s in screens]
    lines.append("/// Load the NUI document.")
    lines.append("pub fn load() -> Document<'static> {")
    lines.append("    Document {")
    lines.append(f'        name: "{escape_rust_string(project.get("name", ""))}",')
    lines.append(f'        version: "{escape_rust_string(doc.get("version", "1.0.0"))}",')
    lines.append("        screens: &[")
    for name in screen_names:
        lines.append(f"            screen_{name}(),")
    lines.append("        ],")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # State constants
    if states:
        lines.append("/// Document-level state variables.")
        lines.append("pub mod state {")
        for key, value in states.items():
            k = escape_rust_string(key)
            v = escape_rust_string(str(value))
            lines.append(f'    pub const {k.upper()}: &str = "{v}";')
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.nstudio> [output.rs]",
              file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(input_path, "r", encoding="utf-8") as f:
        doc = json.load(f)

    rust_code = generate_document(doc)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(rust_code)
        line_count = rust_code.count("\n") + 1
        print(f"Generated {output_path} ({line_count} lines)")
    else:
        print(rust_code)


if __name__ == "__main__":
    main()
