#!/usr/bin/env python3
"""Generate a C++ header from a NUI (.nstudio) document.

This is a NUI → native code exporter for the C++ runtime target
(NyHAL/NyCore layer). It reads a .nstudio file and produces a C++
header that defines the component tree as constexpr data, ready for
a C++ NUI runtime to consume.

Usage:
    python3 tools/generate_cpp.py <input.nstudio> [output.hpp]

The generated C++ code defines:
- Layout, Property, Component, Screen, and Document structs
- constexpr data for the full component tree
- A load() function that returns the document

This follows the same pattern as generate_rust.py but targets the
C++ side of the Nyrqis platform (ADR-0020 §6).

References:
- ADR-0020: language choices (C++ for NyHAL, §6)
- NUI-SCHEMA: component tree structure
"""

import json
import os
import sys
from typing import Any, Dict, List


def escape_cpp_string(s: str) -> str:
    """Escape a string for C++ string literals."""
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\t", "\\t"))


def generate_component(comp: Dict[str, Any], indent: int = 0) -> str:
    """Generate C++ code for a single component."""
    pad = "    " * indent
    comp_id = escape_cpp_string(comp.get("id", ""))
    comp_type = escape_cpp_string(comp.get("type", ""))
    layout = comp.get("layout", {})
    props = comp.get("properties", {})
    events = comp.get("events", {})
    children = comp.get("children", [])

    lines = []
    lines.append(f"{pad}Component{{")
    lines.append(f'{pad}    .id = "{comp_id}",')
    lines.append(f'{pad}    .type = "{comp_type}",')
    lines.append(f"{pad}    .layout = Layout{{")
    lines.append(f"{pad}        .x = {layout.get('x', 0)},")
    lines.append(f"{pad}        .y = {layout.get('y', 0)},")
    lines.append(f"{pad}        .width = {layout.get('width', 100)},")
    lines.append(f"{pad}        .height = {layout.get('height', 30)},")
    lines.append(f"{pad}    }},")

    # Properties
    if props:
        lines.append(f"{pad}    .properties = {{")
        for key, value in props.items():
            k = escape_cpp_string(key)
            v = escape_cpp_string(str(value))
            lines.append(f'{pad}        Property{{"{k}", "{v}"}},')
        lines.append(f"{pad}    }},")
    else:
        lines.append(f"{pad}    .properties = {{}},")

    # Events
    if events:
        lines.append(f"{pad}    .events = {{")
        for key, value in events.items():
            k = escape_cpp_string(key)
            v = escape_cpp_string(str(value))
            lines.append(f'{pad}        Property{{"{k}", "{v}"}},')
        lines.append(f"{pad}    }},")
    else:
        lines.append(f"{pad}    .events = {{}},")

    # Children
    if children:
        lines.append(f"{pad}    .children = {{")
        for child in children:
            lines.append(generate_component(child, indent + 2))
            lines.append(f"{pad}        ,")
        lines.append(f"{pad}    }},")
    else:
        lines.append(f"{pad}    .children = {{}},")

    lines.append(f"{pad}}}")
    return "\n".join(lines)


def generate_document(doc: Dict[str, Any]) -> str:
    """Generate a complete C++ header from a NUI document."""
    project = doc.get("project", {})
    screens = doc.get("screens", [])
    states = doc.get("states", {})
    behaviors = doc.get("behaviors", [])
    bindings = doc.get("bindings", [])

    lines = []
    lines.append("// Auto-generated by generate_cpp.py — DO NOT EDIT")
    lines.append(f"// Source: {project.get('name', 'NUI Document')}")
    lines.append(f"// Version: {doc.get('version', '1.0.0')}")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("#include <string_view>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("namespace nyrqis::nui {")
    lines.append("")

    # Layout struct
    lines.append("/// Layout coordinates for a component.")
    lines.append("struct Layout {")
    lines.append("    double x = 0;")
    lines.append("    double y = 0;")
    lines.append("    double width = 100;")
    lines.append("    double height = 30;")
    lines.append("};")
    lines.append("")

    # Property struct
    lines.append("/// A key-value property pair.")
    lines.append("struct Property {")
    lines.append("    std::string_view key;")
    lines.append("    std::string_view value;")
    lines.append("};")
    lines.append("")

    # Component struct (recursive)
    lines.append("/// A NUI component with its properties and children.")
    lines.append("struct Component {")
    lines.append("    std::string_view id;")
    lines.append("    std::string_view type;")
    lines.append("    Layout layout;")
    lines.append("    std::vector<Property> properties;")
    lines.append("    std::vector<Property> events;")
    lines.append("    std::vector<Component> children;")
    lines.append("};")
    lines.append("")

    # Screen struct
    lines.append("/// A NUI screen with a root component tree.")
    lines.append("struct Screen {")
    lines.append("    std::string_view id;")
    lines.append("    double width = 0;")
    lines.append("    double height = 0;")
    lines.append("    Component root;")
    lines.append("};")
    lines.append("")

    # Document struct
    lines.append("/// The complete NUI document.")
    lines.append("struct Document {")
    lines.append("    std::string_view name;")
    lines.append("    std::string_view version;")
    lines.append("    std::vector<Screen> screens;")
    lines.append("};")
    lines.append("")

    # Generate screen factory functions
    for screen in screens:
        screen_id = escape_cpp_string(screen.get("id", ""))
        size = screen.get("size", {})
        root = screen.get("root", {})

        lines.append(f"/// Screen: {screen_id}")
        lines.append(f"inline Screen make_screen_{screen_id}() {{")
        lines.append(f"    return Screen{{")
        lines.append(f'        .id = "{screen_id}",')
        lines.append(f"        .width = {size.get('width', 0)},")
        lines.append(f"        .height = {size.get('height', 0)},")
        lines.append(f"        .root = {generate_component(root, 2)},")
        lines.append(f"    }};")
        lines.append(f"}}")
        lines.append("")

    # Generate document constructor
    screen_names = [escape_cpp_string(s.get("id", "")) for s in screens]
    lines.append("/// Load the NUI document.")
    lines.append("inline Document load() {")
    lines.append("    return Document{")
    lines.append(f'        .name = "{escape_cpp_string(project.get("name", ""))}",')
    lines.append(f'        .version = "{escape_cpp_string(doc.get("version", "1.0.0"))}",')
    lines.append("        .screens = {")
    for name in screen_names:
        lines.append(f"            make_screen_{name}(),")
    lines.append("        },")
    lines.append("    };")
    lines.append("}")
    lines.append("")

    # State constants
    if states:
        lines.append("/// Document-level state variables.")
        lines.append("struct State {")
        for key, value in states.items():
            k = escape_cpp_string(key)
            v = escape_cpp_string(str(value))
            lines.append(f'    static constexpr auto {k} = "{v}";')
        lines.append("};")
        lines.append("")

    lines.append("}  // namespace nyrqis::nui")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.nstudio> [output.hpp]",
              file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(input_path, "r", encoding="utf-8") as f:
        doc = json.load(f)

    cpp_code = generate_document(doc)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(cpp_code)
        line_count = cpp_code.count("\n") + 1
        print(f"Generated {output_path} ({line_count} lines)")
    else:
        print(cpp_code)


if __name__ == "__main__":
    main()
