#!/usr/bin/env python3
"""Generate a Python module from a NUI (.nstudio) document.

This is a NUI → native code exporter for the Python runtime target
(tooling, testing, developer tools, build tools per ADR-0020). It
reads a .nstudio file and produces a Python module that defines the
component tree as dataclass instances.

Usage:
    python3 tools/generate_python.py <input.nstudio> [output.py]

The generated Python code defines:
- Layout, Property, Component, Screen, and Document dataclasses
- Factory functions for each screen
- A load() function returning the complete document
- State constants as a frozen dataclass

This follows the same pattern as generate_rust.py and generate_cpp.py
but targets the Python side of the Nyrqis platform.

References:
- ADR-0020: language choices (Python for tooling/testing)
- NUI-SCHEMA: component tree structure
"""

import json
import os
import sys
from typing import Any, Dict


def escape_py_string(s: str) -> str:
    """Escape a string for Python string literals."""
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\t", "\\t"))


def generate_component(comp: Dict[str, Any], indent: int = 0) -> str:
    """Generate Python code for a single component."""
    pad = "    " * indent
    comp_id = escape_py_string(comp.get("id", ""))
    comp_type = escape_py_string(comp.get("type", ""))
    layout = comp.get("layout", {})
    props = comp.get("properties", {})
    events = comp.get("events", {})
    children = comp.get("children", [])

    lines = []
    lines.append(f"{pad}Component(")
    lines.append(f'{pad}    id="{comp_id}",')
    lines.append(f'{pad}    type="{comp_type}",')
    lines.append(f"{pad}    layout=Layout(")
    lines.append(f"{pad}        x={layout.get('x', 0)},")
    lines.append(f"{pad}        y={layout.get('y', 0)},")
    lines.append(f"{pad}        width={layout.get('width', 100)},")
    lines.append(f"{pad}        height={layout.get('height', 30)},")
    lines.append(f"{pad}    ),")

    # Properties
    if props:
        lines.append(f"{pad}    properties={{")
        for key, value in props.items():
            k = escape_py_string(key)
            v = escape_py_string(str(value))
            lines.append(f'{pad}        "{k}": "{v}",')
        lines.append(f"{pad}    }},")
    else:
        lines.append(f"{pad}    properties={{}},")

    # Events
    if events:
        lines.append(f"{pad}    events={{")
        for key, value in events.items():
            k = escape_py_string(key)
            v = escape_py_string(str(value))
            lines.append(f'{pad}        "{k}": "{v}",')
        lines.append(f"{pad}    }},")
    else:
        lines.append(f"{pad}    events={{}},")

    # Children
    if children:
        lines.append(f"{pad}    children=[")
        for child in children:
            lines.append(generate_component(child, indent + 2))
            lines.append(f"{pad},")
        lines.append(f"{pad}    ],")
    else:
        lines.append(f"{pad}    children=[],"  )

    lines.append(f"{pad})")
    return "\n".join(lines)


def generate_document(doc: Dict[str, Any]) -> str:
    """Generate a complete Python module from a NUI document."""
    project = doc.get("project", {})
    screens = doc.get("screens", [])
    states = doc.get("states", {})

    lines = []
    lines.append('"""Auto-generated by generate_python.py — DO NOT EDIT')
    lines.append(f"Source: {project.get('name', 'NUI Document')}")
    lines.append(f"Version: {doc.get('version', '1.0.0')}")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from dataclasses import dataclass, field")
    lines.append("from typing import Any, Dict, List")
    lines.append("")
    lines.append("")

    # Layout dataclass
    lines.append("@dataclass(frozen=True)")
    lines.append("class Layout:")
    lines.append('    """Layout coordinates for a component."""')
    lines.append("    x: float = 0")
    lines.append("    y: float = 0")
    lines.append("    width: float = 100")
    lines.append("    height: float = 30")
    lines.append("")
    lines.append("")

    # Component dataclass
    lines.append("@dataclass")
    lines.append("class Component:")
    lines.append('    """A NUI component with its properties and children."""')
    lines.append('    id: str = ""')
    lines.append('    type: str = ""')
    lines.append("    layout: Layout = field(default_factory=Layout)")
    lines.append("    properties: Dict[str, Any] = field(default_factory=dict)")
    lines.append("    events: Dict[str, str] = field(default_factory=dict)")
    lines.append("    children: List[Component] = field(default_factory=list)")
    lines.append("")
    lines.append("")

    # Screen dataclass
    lines.append("@dataclass")
    lines.append("class Screen:")
    lines.append('    """A NUI screen with a root component tree."""')
    lines.append('    id: str = ""')
    lines.append("    width: float = 0")
    lines.append("    height: float = 0")
    lines.append("    root: Component = field(default_factory=Component)")
    lines.append("")
    lines.append("")

    # Document dataclass
    lines.append("@dataclass")
    lines.append("class Document:")
    lines.append('    """The complete NUI document."""')
    lines.append('    name: str = ""')
    lines.append('    version: str = "1.0.0"')
    lines.append("    screens: List[Screen] = field(default_factory=list)")
    lines.append("")
    lines.append("")

    # State dataclass
    if states:
        lines.append("@dataclass(frozen=True)")
        lines.append("class State:")
        lines.append('    """Document-level state variables."""')
        for key, value in states.items():
            k = escape_py_string(key)
            v = escape_py_string(str(value))
            lines.append(f'    {k}: str = "{v}"')
        lines.append("")
        lines.append("")

    # Generate screen factory functions
    for screen in screens:
        screen_id = escape_py_string(screen.get("id", ""))
        size = screen.get("size", {})
        root = screen.get("root", {})

        lines.append(f"def make_screen_{screen_id}() -> Screen:")
        lines.append(f'    """Screen: {screen_id}"""')
        lines.append("    return Screen(")
        lines.append(f'        id="{screen_id}",')
        lines.append(f"        width={size.get('width', 0)},")
        lines.append(f"        height={size.get('height', 0)},")
        lines.append(f"        root={generate_component(root, 2)},")
        lines.append("    )")
        lines.append("")
        lines.append("")

    # Generate document constructor
    screen_names = [escape_py_string(s.get("id", "")) for s in screens]
    lines.append("def load() -> Document:")
    lines.append('    """Load the NUI document."""')
    lines.append("    return Document(")
    lines.append(f'        name="{escape_py_string(project.get("name", ""))}",')
    lines.append(f'        version="{escape_py_string(doc.get("version", "1.0.0"))}",')
    lines.append("        screens=[")
    for name in screen_names:
        lines.append(f"            make_screen_{name}(),")
    lines.append("        ],")
    lines.append("    )")
    lines.append("")
    lines.append("")

    # State instance
    if states:
        lines.append("STATE = State()")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <input.nstudio> [output.py]",
              file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(input_path, "r", encoding="utf-8") as f:
        doc = json.load(f)

    py_code = generate_document(doc)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(py_code)
        line_count = py_code.count("\n") + 1
        print(f"Generated {output_path} ({line_count} lines)")
    else:
        print(py_code)


if __name__ == "__main__":
    main()
